server:
  port: 8083

spring:
  application:
    name: unit-test-service
  datasource:
    url: jdbc:h2:mem:unittest
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# AWS Configuration
aws:
  region: us-east-1
  access-key: ${AWS_ACCESS_KEY_ID:your-access-key}
  secret-key: ${AWS_SECRET_ACCESS_KEY:your-secret-key}
  s3:
    bucket: ${AWS_S3_BUCKET:my-users-meshops-bucket}

# Application Properties
app:
  runner:
    s3-code-path: code/meshops/runner.py
    instance-type: t3.medium
    ami-id: ami-0c02fb55956c7d316
    security-group-id: sg-default
    subnet-id: subnet-default
    key-name: default-key

logging:
  level:
    com.mesh.unittest: DEBUG
    software.amazon.awssdk: WARN
